services:
    doctrine_stats.data_collector.stats:
        class: steevanb\DoctrineStats\Bridge\DoctrineStatsBundle\DataCollector\DoctrineStatsCollector
        arguments: [ '@doctrine_stats.logger.sql', '@doctrine' ]
        public: false
        tags:
            -
                name: data_collector
                id: doctrine_stats
                template: 'DoctrineStatsBundle:DataCollector:template.html.twig'
                priority: 249

    doctrine_stats.event_subscriber.doctrine:
        class: steevanb\DoctrineStats\EventSubscriber\DoctrineEventSubscriber
        arguments: [ '@doctrine_stats.data_collector.stats' ]
        tags:
            - { name: doctrine.event_subscriber }

    doctrine_stats.logger.sql:
        class: steevanb\DoctrineStats\Doctrine\DBAL\Logger\SqlLogger
        public: false
